@startuml
!include .\\Program.puml
!include .\\Controllers\CardController.puml
!include .\\Controllers\PrinterController.puml
!include .\\Controllers\UserController.puml
!include .\\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\obj\Debug\net8.0\WebAPI.AssemblyInfo.puml
!include .\\obj\Debug\net8.0\WebAPI.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0\WebAPI.MvcApplicationPartsAssemblyInfo.puml
@enduml
